### ISSUE TITLE
feat: display helia metrics in probelab

### ISSUE THREAD

**Issue by SgtPooki** [ipfs/helia#112]
Note: the probelab side of things is being documented at https://pl-strflt.notion.site/Helia-as-part-of-CMI-4ccbd109ce404f8fa4b4b02fd8af0b3f

```[tasklist]
### Tasks
- [x] Discover how Probelab is generating their metrics (talk with https://github.com/iand and https://github.com/dennis-tra)
- [x] Document gaps/blockers that exist in helia or https://github.com/plprobelab/caracol
- [x] Devise & finalize plan for getting Helia metrics into probelab
- [x] Execute the plan
- [ ] Create js-libp2p docker image in plprobelab/parsec
- [ ] figure out why js-libp2p agent_version isn't showing in probelab metrics (should be similar to js-libp2p/0.0.0 UserAgent=v16.15.1)
- [ ] Document Helia configuration on probelab.io: https://github.com/plprobelab/website/pull/85
```

**Comment by SgtPooki** [comment]
### Notes from chat with @dennis-tra and @iand:

1. Already doing 3 experiments for DHT (parsec)
    1. Scheduler goes around to nodes 1x1, please provide CID, then waits, and asks other regions to request CID from DHT, and measures latency. (default impl, accelerated, and oppProv)
        1. We could add a 4th one, which is helia fleet. then we could test providing from helia, and requesting from kubo, and vice versa.
        2. Deployed via docker image (github://plprobelab/parsec)
            1. 4 methods we need to implement in helia docker image: [https://github.com/plprobelab/parsec/blob/848e87a7dbb4652b999f855293cd8ac06e69b5f7/pkg/server/server.go#L180-L184](https://github.com/plprobelab/parsec/blob/848e87a7dbb4652b999f855293cd8ac06e69b5f7/pkg/server/server.go#L180-L184)
    2. retrieval success rate
    3. provide success rate
    4. time to first provider record

**Comment by SgtPooki** [comment]
Note: This should be moved to the js-libp2p repo

**Comment by dennis-tra** [comment]
@SgtPooki @achingbrain 

I just finished documenting our `parsec` measurement tool. I have added a section [`Implementing a Server`](https://github.com/plprobelab/parsec#implementing-a-server) outlining the steps you'd need to take to be compatible with the rest of the infra. It's three things:

1. Implement three HTTP endpoints. Documented [here](https://github.com/plprobelab/parsec/blob/main/server.yaml) as an OpenAPI spec. For a rendering head over to https://editor-next.swagger.io/ -> File -> Import URL... -> paste: `https://raw.githubusercontent.com/plprobelab/parsec/main/server.yaml`
2. Write an entry to our postgres database (so a postgres client is necessary unfortunately :/)
3. Refresh a heartbeat.

**Comment by dennis-tra** [comment]
Hi @SgtPooki, I just wanted to check-in and see if this is still on the roadmap :) I'm asking just out of curiosity because I would love to see a performance comparison 👍

**Comment by yiannisbot** [comment]
@SgtPooki quick follow up to see if this will be prioritised from your end so that we include it at probelab.io and allocate any resources to help out and get it to the finish line. Thanks!

**Comment by SgtPooki** [comment]
This is in progress now and we should see some results in 2-3 hours hopefully.

**Comment by BigLep** [comment]
@SgtPooki : what's the relationship between this issue and https://github.com/ipfs/helia/issues/275 ?

**Comment by SgtPooki** [comment]
This is a duplicate, closing this
