### ISSUE TITLE
fix: helia api docs have no blank pages

### ISSUE THREAD

**Issue by SgtPooki** [ipfs/helia#176]
## Goals

tsdoc generated documentation at https://ipfs.github.io/helia/ should present users with a more intuitive experience.

```[tasklist]
### Tasks
- [x] fix empty pages
- [x] fix landing pages
- [x] warning The --name option was not specified, and no package.json was found. Defaulting project name to "Documentation".
- [ ] Investigate the blank pages after building on CI
- [ ] investigate: https://ipfs.github.io/helia-ipns/
```

**Comment by BigLep** [comment]
@SgtPooki : I'm reopening because when I go to https://ipfs.github.io/helia/ , I still don't get a useful landing page.

**Comment by SgtPooki** [comment]
re-opening just to confirm that ipfs.github.io/helia has the issue resolved.

**Comment by SgtPooki** [comment]
Need https://github.com/ipfs/helia/actions/runs/5549008917 to finish, and then a new https://github.com/ipfs/helia/actions/workflows/pages/pages-build-deployment should kick off, and then we can check https://ipfs.github.io/helia/

**Comment by SgtPooki** [comment]
we have a landing page now, and 404s are gone

**Comment by BigLep** [comment]
I'm reopening because when I go to https://ipfs.github.io/helia/index.html, I don't actually see any "API docs" along the line of `returnType functionName(argName)`.  (I accept I am maybe blind here.)

**Comment by SgtPooki** [comment]
it appears that some changes were made at some point (@achingbrain ?)

**Comment by achingbrain** [comment]
I updated to the latest version of TypeDoc.  Very strange this, I get the API docs you'd expect when building them locally but it looks like not in CI?

**Comment by achingbrain** [comment]
This looks healthy again, although I'm still at a loss as to what upset TypeDoc so much as to cause the docs to disappear in the first place.

**Comment by achingbrain** [comment]
Closing as the landing page for the API docs is no longer blank.

**Comment by achingbrain** [comment]
TypeDoc has been upgraded in Aegir, as modules are updated and their docs re-published, the blank pages will go away.
