### ISSUE TITLE
TODO items for Community Meetings

### ISSUE THREAD

**Issue by tinytb** [ipfs/helia#25]
- [x] 1. Make sure they are easily discoverable (including link from README)
- [x] 2. Recorded and shared afterwards in dedicated Helia channel (and link this from README)
- [ ] 3. It would be great if they could have the tone of a sprint demo where folks can share: here was the problem to solve, here is that problem fixed with a demo, what next steps are.  We want to get to a place where people are making a commitment to get certain work done for the next demo/meetup.

**Comment by SgtPooki** [comment]
item 1 done by https://github.com/ipfs/helia/pull/80
item 2 is basically a copy of item 1, we link to youtube videos, and publish helia WG meetings to youtube videos


item 3: we should encourage more devs using helia to join the WG call and share demos of what they're building.

**Comment by SgtPooki** [comment]
FYI I added a section to Helia WG meeting notes template to ask for demos in the current session, and to talk about future demos for future sessions. Closing this
