### ISSUE TITLE
Create design doc for "helia with trustless gateway HTTP support"

### ISSUE THREAD

**Issue by SgtPooki** [ipfs/helia#272]
```[tasklist]
### Tasks
- [x] create diagram of current flow and confirm with @achingbrain
- [x] create diagram of new flow and confirm impl with @achingbrain
- [ ] Update diagram at https://github.com/ipfs/helia/blob/ecdb46e0d40df86a59e58fcdfb701db6e36d36e6/README.md?plain=1#L151-L177
```

**Comment by SgtPooki** [comment]
Rough flowchart of getting a block using Helia as things currently stand:

```mermaid
flowchart TD
    %% getting a single block from helia
    A[Application] -->|get block| B[Helia module]
    B -->|get block| C[Helia.BlockStorage]
    C -->|get block| D[Helia.NetworkedStorage]
    D --> E{BlockStorage.has}
    E -->|have block| A
    E -->|No| F{Online & Bitswap}
    F -->|No| G[End]
    F -->|Yes| H{bitswap.WANT}
    H -->|get block| H
    H -->|have block| A
```

**Comment by SgtPooki** [comment]
rough flowchart of what expected flow will be once #274 is done:

```mermaid
flowchart TD
    %% getting a single block from helia after https://github.com/ipfs/helia/issues/274
    A[Application] -->|get block| B[Helia module]
    B -->|get block| C[Helia.BlockStorage]
    C -->|get block| D[Helia.NetworkedStorage]
    D --> E{BlockStorage.has}
    E -->|have block| A
    E -->|No| F{Online}
    F -->|No| G[End]
    F -->|yes2| H{Use byteProviders}
    H -->|BitSwap| H1{bitswap.WANT}
    H1 -->|get block| H1
    I[any byteProvider returns success]
    H1 -->|have block| I
    H -->|OtherMethod| H2{Any Impl}
    H2 -->|have block| I
    H -->|TrustLessGateway| H3{dweb.link}
    H3 -->|have block| I
    I -->|have block| A
```

https://mermaid.live/edit#pako:eNp9klFv2jAQgP-KZalvNCEhQJeHSVBoQdroJJgqjfBgkguxSOzIvpSlgf8-kzQVMG1-ycX33XdnyxUNZQTUp3EqD2HCFJLVJBDErLs7sgNELnaEEW0-KZBtKsM9iZXMSAIpZ4TFCIokiLn2bXvHMSm2Vigzm-extmvG5loXoG136DXi0XqU5ykPGXIpNuT-_uvRNGrcRzJez2pzJqMihU1TMr6lHhvKGp9_lygV27Xs4y07-WAXgAep9hBd85MzT6bVpcpKmD416WmtS9gbtL7RZWIhj-SpehEpF_BR8fSZeF5PRbS53C1Bu0cyq35qoysRfij5xiNQbbdZTY05Lg8sN6BTbTlqE1uvo8WqhZzbI86cJjNfM1FeiYkCLJTQRBdhCFpvrhSXx5pfTvCCCajvgImMjN2tRkY7z_K0ncD9f_lKFRq_mXbPDOHASuPoVdEBtpa5p30r6f1LMv_7zmmHZqAyxiPzWKszFlAzYwYB9U0YQcyKFAMaiJNBWYFyWYqQ-qgK6NAij8wgE852imXUj1mqzW7OBPUr-pv6Tm9gfen1nb7X9dzhg-t2aEn9gTXwnN7Q6_bdgffQHfZPHfoupRE4dfGvOj53OP0BzmMOHg

**Comment by SgtPooki** [comment]
@achingbrain could use a peek at this. i'm planning on making the change in `networked-storage.ts` since that's where the networking stuff happens.. 

I was also thinking of wrapping bitswap with a `byteProvider` implementation, but maybe that can wait for later?

**Comment by SgtPooki** [comment]
The rest of the work/discussion here is being handled by https://github.com/ipfs/helia/issues/274

**Comment by BigLep** [comment]
@SgtPooki : can we get this issue closed?  I assume just need to get this diagram checked into the Helia repo?

**Comment by SgtPooki** [comment]
@BigLep yea, it's mostly waiting on #274.. I can move any tasks left from this into that issue or https://github.com/ipfs/helia/issues/287
