### ISSUE TITLE
Update Helia to fallback to trustless HTTP gateways

### ISSUE THREAD

**Issue by SgtPooki** [ipfs/helia#274]
discussed in https://pl-strflt.notion.site/Helia-reliable-retrieval-technical-design-golden-path-255-15c4d3c25a404a85b6db8bf3f8d1f310?pvs=4

Should do https://github.com/ipfs/helia/issues/272 first

```[tasklist]
### Tasks
- [x] create ByteProvider interface
- [x] add `byteProviders` config key to Helia configuration object
- [x] Emit onProgress events that specify which provider (dht, gateway url, etc..) is returning bytes
- [x] implement default fallback byteProvider for a trustless http gateway
- [x] clarify with @achingbrain whether we need to verify bytes or if this is already handled
- [ ] https://github.com/ipfs/helia/pull/276
- [ ] https://github.com/ipfs/helia/pull/280
- [ ] https://github.com/ipfs/helia/pull/281
- [ ] https://github.com/ipfs/helia/pull/284
- [ ] https://github.com/ipfs/helia/pull/285
- [ ] https://github.com/ipfs/helia/issues/287
```

**Comment by SgtPooki** [comment]
https://github.com/ipfs/helia/pull/276 is still in progress, but I could use some input from @achingbrain that the direction i'm heading in works before I flesh everything out

**Comment by SgtPooki** [comment]
some of this work was moved to https://github.com/ipfs/helia/pull/280 and also https://github.com/ipfs/helia/pull/281 on top of that

**Comment by SgtPooki** [comment]
The work here is done and merged into the `main` branch but is not released on `@latest` tag on npm yet. You can experiment with the changes made on the `@next` tag.

**Comment by BigLep** [comment]
@SgtPooki : what are the conditions for closing this?
1. Helia release?
2. Any additional docs we need to add? (or is that already in the API docs)?  (If already in the API docs, can you point me to the relevant ones so I can look at them from a user's point of view?)
3. ?

Thanks

**Comment by SgtPooki** [comment]
> @SgtPooki : what are the conditions for closing this?
> 
> 1. Helia release?

Yep. I discussed this with Alex and we talked about how we would let this sit in `@next` tagged release and request devs try it out for a bit before merging it. There's no guarantee that devs will try it, but I *plan* to.

> 2. Any additional docs we need to add? (or is that already in the API docs)?  (If already in the API docs, can you point me to the relevant ones so I can look at them from a user's point of view?)

Docs are not published yet but should be in https://helia.io/interfaces/helia.HeliaInit.html & https://helia.io/modules/_helia_interface.blocks.html when they are. You can see the docs that will be mentioned in the source here:

* https://github.com/ipfs/helia/blob/43932a54036dafdf1265b034b30b12784fd22d82/packages/helia/src/index.ts#L95-L99
* https://github.com/ipfs/helia/blob/43932a54036dafdf1265b034b30b12784fd22d82/packages/interface/src/blocks.ts#L66-L90


It could be worth adding some info to the wiki or README including the diagrams at https://github.com/ipfs/helia/issues/272 once we decide we will release these changes.

**Comment by pcfreak30** [comment]
I can actually confirm the trustless gateway works. The only issue are some of the gateways don't properly allow CORS which causes issues in browser when fetching CAR data.

**Comment by SgtPooki** [comment]
@pcfreak30 thanks for the update! Which gateways were causing issues?

**Comment by SgtPooki** [comment]
Yea, will do. FYI, you can limit the gateway urls you enable by setting `blockBrokers` in the config object passed to `createHelia`:

```
import { createHelia, type Helia } from 'helia'
import { bitswap, trustlessGateway } from 'helia/block-brokers'

await createHelia({
      blockBrokers: [
        bitswap(),
        trustlessGateway({ gateways: ['https://dweb.link', 'https://ipfs.io'] })
      ]
    })
```

**Comment by SgtPooki** [comment]
FYI that I threw a quick codepen together that shows this working fine for all default gateways: https://codepen.io/SgtPooki/pen/JjxYpZX

**Comment by pcfreak30** [comment]
I will update if I can replicate in my setup, thanks.

**Comment by pcfreak30** [comment]
@SgtPooki i was able to get a screenshot from a tester.

![image](https://github.com/ipfs/helia/assets/10647/e9c7c930-02c4-4e1a-b699-7427f025a1db)

**Comment by BigLep** [comment]
@SgtPooki : what is needed for closing out this issue?

**Comment by SgtPooki** [comment]
I believe this is done except for https://github.com/ipfs/helia/pull/374. The spec work for other gateways is at https://github.com/ipfs/specs/issues/423. 

closing this
