### ISSUE TITLE
Create infrastructure for testing and validating retrieval reliability with Helia

### ISSUE THREAD

**Issue by SgtPooki** [ipfs/helia#275]
discussed in https://pl-strflt.notion.site/Reliable-retrieval-monitoring-project-plan-formation-ce2190c2ad054a44b8d0fca7d2cf6006?pvs=4

```[tasklist]
### Tasks
- [x] Phase 0: validate with probelab that they can pull from GitHubContainerRegistry
- [x] Phase 1: create helia nodejs gateway that can work with probelab's tiros
- [x] Phase 1: implement /api/v0/repo/gc to run garbage collection upon request
- [x] Phase 1: respond to `<host>/<namespace>/request` using a simple server
- [x] Phase 1: Tiros support for a Helia gateway: https://github.com/plprobelab/tiros/pull/5
- [x] Phase 1: problab.io testing website using a Helia gateway: https://github.com/plprobelab/probelab-infra/pull/75
- [x] Phase 1: Investigate helia-http-gateway crashing issue. - https://github.com/ipfs/helia-http-gateway/issues/18
- [ ] https://github.com/ipfs/helia-http-gateway/issues/12
- [x] Ensure helia maintainers have access to a graph showing successful helia-http-gateway runs
- [x] Decide on how we want to handle running & displaying 3 separate helia-http-gateway setups with tiros
- [x] Get https://github.com/ipfs/helia-ipns/pull/55 merged and pulled into this repo so we can improve ipns queries.
- [x] Document the Helia configurations run on probelab.io: https://github.com/plprobelab/website/pull/85
- [x] migrate to @helia/verified-fetch -> https://github.com/ipfs/helia-http-gateway/pull/63
```

**Comment by SgtPooki** [comment]
@whizzzkid FYI that the service-worker gateway version should be secondary to the nodejs work.

**Comment by BigLep** [comment]
Thanks for sharing @whizzzkid .  I agree there is something here.  I'd have to think with a clear head whether this should live under helia.io.

What I do think worth doing is showing the diagram of interaction for the Tiros case.  Ideally the Probelab Tiros case has no dependency on software outside of what is distributed in the docker image.  It shouldn't be impacted by whether helia.io is up for fetching `/init.js` or `/install.html`.  I think we should keep that all local to the Tiros docker image for now and get it working.  

Once we have worked out the kinds there, we look at expanding further.

**Comment by BigLep** [comment]
A few comments in circling back on this:
1. General comments on "helia-docker" name and scope: https://github.com/ipfs/helia-docker/issues/12
2. How can we get the phase 1 functionality deployed so we can start seeing retrievability numbers?
3. I know currently we are only in phase 1 of using Helia in Node.  Can we get numbers though for how much reliability/performance improves whether we enable "trustless" gateway fallback or not.  Basically, I think we should run the docker in one configuration where trustless fallback isn't enabled, and one where it is.
4. How are we doing with phase 2 (testing retrieving from the browser without any dependency on an external site like helia.io)?  Is that work being tracked somewhere else or here?
5. As part of phase 2, lets create a diagram like [here](https://github.com/ipfs/helia/issues/275#issuecomment-1747965736), but without helia.io.
6. I added a couple of subtasks to the description of this issue.  Please add others that are relevant for tracking this completion.

**Comment by SgtPooki** [comment]
> 2. How can we get the phase 1 functionality deployed so we can start seeing retrievability numbers?

deployed to probelab tiros and we're getting numbers now, but there are some remaining issues.

> 3. I know currently we are only in phase 1 of using Helia in Node. Can we get numbers though for how much reliability/performance improves whether we enable "trustless" gateway fallback or not. Basically, I think we should run the docker in one configuration where trustless fallback isn't enabled, and one where it is.

We can get these numbers but would need to work with probelab on deploying a second helia version. we should probably make sure we resolve any crashing issues first

> 4. How are we doing with phase 2 (testing retrieving from the browser without any dependency on an external site like helia.io)? Is that work being tracked somewhere else or here?

This is being tracked in this issue currently but we should spin that out.

> 5. As part of phase 2, lets create a diagram like https://github.com/ipfs/helia/issues/275#issuecomment-1747965736, but without helia.io.

Sounds good.

**Comment by SgtPooki** [comment]
FYI that i'm moving the service worker discussions to https://github.com/ipfs/helia-http-gateway/issues/56 and out of this issue so we can call this done when the dockerized node-side version of helia-http-gateway is done

**Comment by achingbrain** [comment]
Retrieval reliability is now tracked by probelab.
