### ISSUE TITLE
chore: add benchmarks/* to workspaces and update

### ISSUE THREAD

**Issue by SgtPooki** [ipfs/helia#349]
Chatted with Alex about this today at the end of Helia WG.

We should update benchmark dependencies and remove js-ipfs from the benchmarks before we finalize this

```[tasklist]
### Tasks
- [ ] remove js-ipfs from benchmarks and any other deps 
- [ ] Update js-ipfsd-ctl (@achingbrain to provide more direction here)
- [ ] https://github.com/ipfs/helia/pull/346
- [ ] update benchmarks/add-dir
```
