### ISSUE TITLE
helia@5.x.x release issue

### ISSUE THREAD

**Issue by SgtPooki** [ipfs/helia#586]
- [x] https://github.com/ipfs/helia/issues/585
- [x] https://github.com/ipfs/helia/pull/630
- [x] https://github.com/ipfs/helia/pull/447
- [x] Migration guide - https://github.com/ipfs/helia/wiki/Upgrade-guide-from-Helia-4.0.0-to-Helia-5.0.0

## Post release

- [x] Upgrade js-libp2p examples - https://github.com/libp2p/js-libp2p-examples/pull/170#pullrequestreview-2310289205

## Related

* https://github.com/libp2p/js-libp2p/issues/2626
